version: '3'

services:
  node-app:
    build: .
    entrypoint: wait-for db:3306 -t 40 -- ./start.sh
    container_name: node-app
    tty: true
    networks: 
      - node-network
      
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=myDatabase
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-start.sh:/scripts/nginx-start.sh:rw
    networks:
      - node-network

networks: 
  node-network:
    driver: bridge